### ISSUE TITLE
Impossible to create a player

### ISSUE THREAD

**Issue by Lhorus6** [OpenEx-Platform/openex#405] opened 2023-11-24 15:27 UTC
## Description

It's impossible to create a player. When you press the "Create" button, nothing happens.

## Environment

OpenEX 3.4.1-SNAPSHOT

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on "Players"
2. Click on "+"
3. Fill in all the fields
4. Click on "CREATE"
5. -> Nothing happens

**Comment by RomuDeuxfois** [comment] 2023-11-24 15:36
Duplicate of https://github.com/OpenEx-Platform/openex/issues/404

**Closed** 2023-11-24 15:35 UTC
Labels: bug, filigran team
